# Minimal seccomp profile: allow only essential syscalls for user-space code execution
SECCOMP_PROFILE = {
    "defaultAction": "SCMP_ACT_ERRNO",
    "syscalls": [
        {"name": "read", "action": "SCMP_ACT_ALLOW"},
        {"name": "write", "action": "SCMP_ACT_ALLOW"},
        {"name": "open", "action": "SCMP_ACT_ALLOW"},
        {"name": "openat", "action": "SCMP_ACT_ALLOW"},
        {"name": "close", "action": "SCMP_ACT_ALLOW"},
        {"name": "execve", "action": "SCMP_ACT_ALLOW"},
        {"name": "brk", "action": "SCMP_ACT_ALLOW"},
        {"name": "mmap", "action": "SCMP_ACT_ALLOW"},
        {"name": "munmap", "action": "SCMP_ACT_ALLOW"},
        {"name": "exit_group", "action": "SCMP_ACT_ALLOW"},
        {"name": "fstat", "action": "SCMP_ACT_ALLOW"},
        {"name": "lseek", "action": "SCMP_ACT_ALLOW"},
        {"name": "rt_sigreturn", "action": "SCMP_ACT_ALLOW"},
        {"name": "clone", "action": "SCMP_ACT_ALLOW"},
        {"name": "wait4", "action": "SCMP_ACT_ALLOW"},
        {"name": "getpid", "action": "SCMP_ACT_ALLOW"},
        {"name": "arch_prctl", "action": "SCMP_ACT_ALLOW"},
        {"name": "set_tid_address", "action": "SCMP_ACT_ALLOW"},
        {"name": "set_robust_list", "action": "SCMP_ACT_ALLOW"},
        {"name": "prctl", "action": "SCMP_ACT_ALLOW"},
        {"name": "uname", "action": "SCMP_ACT_ALLOW"},
        {"name": "access", "action": "SCMP_ACT_ALLOW"},
        {"name": "getcwd", "action": "SCMP_ACT_ALLOW"},
        {"name": "readlink", "action": "SCMP_ACT_ALLOW"},
        {"name": "mprotect", "action": "SCMP_ACT_ALLOW"},
        {"name": "sigaltstack", "action": "SCMP_ACT_ALLOW"},
        {"name": "statfs", "action": "SCMP_ACT_ALLOW"},
        {"name": "getdents64", "action": "SCMP_ACT_ALLOW"},
        {"name": "fcntl", "action": "SCMP_ACT_ALLOW"},
        {"name": "ioctl", "action": "SCMP_ACT_ALLOW"},
        {"name": "dup2", "action": "SCMP_ACT_ALLOW"},
        {"name": "pipe", "action": "SCMP_ACT_ALLOW"},
        {"name": "socket", "action": "SCMP_ACT_ALLOW"},  # for localhost-only if needed
        {"name": "connect", "action": "SCMP_ACT_ALLOW"},
        {"name": "sendto", "action": "SCMP_ACT_ALLOW"},
        {"name": "recvfrom", "action": "SCMP_ACT_ALLOW"},
        {"name": "shutdown", "action": "SCMP_ACT_ALLOW"},
        {"name": "bind", "action": "SCMP_ACT_ALLOW"},
        {"name": "listen", "action": "SCMP_ACT_ALLOW"},
        {"name": "accept", "action": "SCMP_ACT_ALLOW"},
        {"name": "getsockname", "action": "SCMP_ACT_ALLOW"},
        {"name": "getpeername", "action": "SCMP_ACT_ALLOW"},
        {"name": "setsockopt", "action": "SCMP_ACT_ALLOW"},
        {"name": "getsockopt", "action": "SCMP_ACT_ALLOW"},
    ],
}
